{"uuid": "32932e3c-3207-4b41-be4f-a5f3ebd4dc19", "children": ["be55e3d8-f1bf-4f03-9306-7c4caabe122d"], "befores": [{"name": "access_web", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.NoSuchDriverException: Message: Unable to obtain chromedriver using Selenium Manager; Message: Unsuccessful command executed: d:\\python\\lib\\site-packages\\selenium\\webdriver\\common\\windows\\selenium-manager.exe --browser chrome --output json.\nrequest or response body error: operation timed out\n; For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors/driver_location\n\n", "trace": "  File \"d:\\python\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"d:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 1130, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"d:\\python\\lib\\site-packages\\_pytest\\fixtures.py\", line 902, in call_fixture_func\n    fixture_result = next(generator)\n  File \"C:\\Users\\今晚打老虎\\Desktop\\pythonProject1\\conftest.py\", line 10, in access_web\n    driver = webdriver.Chrome()\n  File \"d:\\python\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 47, in __init__\n    self.service.path = DriverFinder.get_path(self.service, self.options)\n  File \"d:\\python\\lib\\site-packages\\selenium\\webdriver\\common\\driver_finder.py\", line 44, in get_path\n    raise NoSuchDriverException(f\"Unable to obtain {service.path} using Selenium Manager; {err}\")\n"}, "start": 1688570285436, "stop": 1688570471797}], "start": 1688570285436, "stop": 1688570471875}